language: python
sudo: false
cache:
  directories:
    - eggs
    - downloads
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py --version=2.5.3
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coveralls==0.5
  - coveralls
notifications:
  email:
    - vincent.fretin@gmail.com
